Feat/speed up
deezy-inc/deezy-place pull request #276
Opened 2023-07-21 00:35 UTC by andredevjs

2023-07-21 00:48 UTC, dannydeezy commented
collections page does seem to load pretty quickly

2023-07-21 00:49 UTC, dannydeezy commented
<img width="261" alt="Screenshot 2023-07-20 at 5 48 50 PM" src="https://github.com/deezy-inc/deezy-place/assets/43550949/6f124e5a-0990-44b9-aa5c-c3a20f3a2f69">

the lowercase title doesn't look great, but that's not part of this pr

2023-07-21 00:52 UTC, dannydeezy commented
<img width="1550" alt="Screenshot 2023-07-20 at 5 52 03 PM" src="https://github.com/deezy-inc/deezy-place/assets/43550949/3408f77c-4249-4f70-9179-e4f66fce203d">

These show up as listed but when you click on them, there is no buy button. I wonder if you have introduced a regression in the logic that checks if a listing has been invalidated (by being spent)

2023-07-21 00:53 UTC, dannydeezy commented on src/containers/CollectionLive.js
> -                  const { spent } = await isInscriptionSpent(inscription);
i think this logic never got put back in, hence all those 10k sat listings showing up on the collection page?

2023-07-31 15:07 UTC, habibitcoin requested changes
Still going thru full PR review and code review, but noticed a few things during QA:

-  We are not displaying the value of un-inscribed UTXOs in the wallet any longer 
![image](https://github.com/deezy-inc/deezy-place/assets/114780316/740f078e-227e-4d61-b95c-fd999b99e0a5) 
- Not a regression, but will make new task. You cannot view or send uninscribed UTXOs any longer either
- Something is causing the marketplace page to load slower now


Collections page definitely loads quicker. Need to test loading a wallet with many inscriptions as well.

Also general feedback for the future, lets avoid having multiple linear tasks in a single branch. Leads to them getting backed up.

2023-07-31 17:24 UTC, dannydeezy commented
@andredevjs can you fix merge conflicts please?

2023-08-01 00:26 UTC, closed without merging