feat: rarity
deezy-inc/deezy-place pull request #303
Opened 2023-08-22 20:59 UTC by topether21

2023-08-30 17:18 UTC, topether21 commented on src/assets/scss/elements/_uninscribed_stats.scss
> +  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
<img width="1177" alt="image" src="https://github.com/deezy-inc/deezy-place/assets/126987350/07810d87-4aad-489f-98f6-ceda672b5fda">
? @andredevjs

2023-08-31 16:54 UTC, habibitcoin approved these changes
I think for usability, we need to be able to see the UTXO value somehow
![image](https://github.com/deezy-inc/deezy-place/assets/114780316/07e1e407-e558-4b09-acdb-aef05210b8c2)
Not blocking tho, will log as follow up

Overall, amazing work!! Fix merge conflicts, and lets ship!

2023-08-31 17:02 UTC, habibitcoin requested changes
1 small bug, looks like https://deploy-preview-303.test.deezy.place/inscription/8a8ed539eeba089a64f95a16fb031724474ec4326ae8009bf4ec703d87a94673i0 view bids button isnt working

2023-08-31 23:49 UTC, habibitcoin approved these changes
ready to go!

2023-08-31 23:50 UTC, merged